apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: phpipam-scanner
  name: phpipam-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      role: phpipam-scanner
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        role: phpipam-scanner
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/jontheniceguy/publish-packages/phpipam-python-scanagent:latest
          name: phpipam-scanner
          resources: {}
          env:
            - name: IPAM_SERVER
              value: phpipam.example.org
            - name: IPAM_API_CLIENT
              value: my_api
            - name: IPAM_API_TOKEN
              value: DECAFbad1234567890abcdefghijklmn
            - name: IPAM_API_AGENT_CODE
              value: aabbccddeeffgghhIIJJKKLL12345678
status: {}
